### ISSUE TITLE
По какой-то причине отказывается работать

### ISSUE THREAD

**Issue by reodeza** [golandprog/AIMP-OBS-Widget#1]
Просто не грузится в обс
![image](https://user-images.githubusercontent.com/38606782/173171557-6fa2c999-0e2d-4485-956d-ef3595d23b87.png)
А в браузере показывает
![image](https://user-images.githubusercontent.com/38606782/173171581-9273ae65-8e9c-4421-8cbb-6bbe3f52a9cb.png)

**Comment by Ponywka** [comment]
Сам заметил эту проблему. Связано это с тем, что на OBS 27+ решили обновить плагин браузера, где добавили (вернее включили) блокировку CORS (видно по первому логу). Тут уже надо конкретно засесть или за изучение OBS, или же за изучение плагина для AIMP

**Comment by Ponywka** [comment]
Собственно, если засунуть в папку `${aimp}\Plugins\Remote Control\Web\widget` содержимое виджета, то по адресу `http://localhost:3333/widget/index.html` будет доступен виджет.

**Comment by Ponywka** [comment]
Продублировал тут: https://github.com/Ponywka/AIMP-OBS-Widget/commit/b9ae598bc9a4ef6fce19ca8e648ba061e102663e

**Comment by reodeza** [comment]
Спасибо за помощь, премного благодарен
