### ISSUE TITLE
AIMP Remote Control Doesn't Seem to Work on AIMP5

### ISSUE THREAD

**Issue by ZTL-UwU** [golandprog/AIMP-OBS-Widget#2]
Although the folder `C:\Program Files\AIMP\Plugins\Remote Control` is created, the service on `localhost:3333` does not start, and the Remote Control tab is not in the plugin tab.

![image](https://user-images.githubusercontent.com/49156174/187820534-1c48fc6b-971a-4e4e-be12-c3f48163edd2.png)
![image](https://user-images.githubusercontent.com/49156174/187820633-d02b8498-14ac-46e2-a95b-f40d553006ff.png)

It's not the problem of this repo, but I really want to use this widget.
Maybe there are some ways to work around this?

**Comment by Benjiiben53** [comment]
same problem...

**Comment by Ponywka** [comment]
I think you need install AIMP x32 before use this Plugin. 
I tried it right now and all works good! 
![Screenshot_20221218-153311](https://user-images.githubusercontent.com/26777464/208299031-b0c39fab-8824-4374-88b0-0bc2f8e2c0c6.png)

**Comment by Ponywka** [comment]
I update my AIMP to last version and all works good!
![Screenshot_20221218-154903](https://user-images.githubusercontent.com/26777464/208299313-a4eecc2e-dfa9-4811-bfa5-f87a6f9f2d4e.png)

Please reinstall your AIMP to x32 version. This is mentioned on the site when downloading!
![Screenshot_20221218-155132](https://user-images.githubusercontent.com/26777464/208299401-74d0d1fe-2d08-49df-9a0c-ca9c479a7367.png)

**Comment by PepeParada** [comment]
qué lástima que este plugin ya no está actualizado. Era el MEJOR PLUGIN que había!. Ojalá algun desarrollador quiera y pueda continuarlo.
